name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Publish tag'
        required: true
        type: string
      count:
        description: 'Publish count'
        required: true
        type: string

jobs:
  push_to_registry:
    name: Push Docker image to Aliyun Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Aliyun Docker Hub
        run: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Build and push Docker image
        run : |
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/worldhim/gsuid_core:${{ inputs.tag }}-${{ inputs.count }}
          docker push registry.cn-hangzhou.aliyuncs.com/worldhim/gsuid_core:${{ inputs.tag }}-${{ inputs.count }}
